[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install", "cd frontend && npm install", "cd backend && npm install"]

[phases.build]
cmds = ["npm run build"]
